services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service

  game-service:
    build:
      context: ./game-service
      dockerfile: Dockerfile
    container_name: game-service

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"

  mafia-db:
    image: postgres:18
    container_name: mafia-db

  mafia-rabbitmq:
    image: rabbitmq:4.1-management
    container_name: mafia-rabbitmq
