spring.application.name=gateway-service
server.port=8080
spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=game-service
spring.cloud.gateway.routes[1].uri=http://game-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/game/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
