spring.application.name=game-service
server.forward-headers-strategy=framework
server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://mafia-db:5432/mafia}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA/Hibernate defaults for local dev
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}

# Security JWT Configuration (shared with auth-service)
jwt.secret=${JWT_SECRET:VhUiBCj6kd1Ikwb0CrjgLBWxrW7zVFwqL+IGNnkJtrLXQW4lcZQcxBUyjEVYSLirHrqhUeaipaP8YwjO2+e0Vw==}
jwt.expiration=${JWT_EXPIRATION:60000}

# Enable scheduled tasks
spring.task.scheduling.enabled=${SPRING_TASK_SCHEDULING_ENABLED:false}

# Logging Configuration
logging.level.com.mafia=${LOGGING_LEVEL_COM_MAFIA:DEBUG}
logging.level.org.springframework.web=${LOGGING_LEVEL_SPRING_WEB:DEBUG}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_HIBERNATE_SQL:DEBUG}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOGGING_LEVEL_HIBERNATE_BINDER:TRACE}

# Application Specific Configuration
app.frontend.joinPath=${APP_FRONTEND_JOIN_PATH:/join/}

# RabbitMQ Configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:mafia-rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# Actuator Configuration
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_EXPOSURE_INCLUDE:health}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:when-authorized}
